-- CourseHeat Supabase schema
-- Passwordless SRM email auth only. Never collect SRM portal credentials.

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.professors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  department_id bigint references public.departments(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (name, department_id)
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique check (lower(email) like '%@srmist.edu.in'),
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id text primary key,
  code text not null,
  title text not null,
  department text not null,
  professor text not null,
  professor_id uuid references public.professors(id) on delete set null,
  semester text not null check (semester in ('Fall', 'Spring', 'Summer', 'Winter')),
  year integer not null check (year between 2020 and 2100),
  enrollment integer not null default 0 check (enrollment >= 0),
  avg_rating numeric(3,1) not null default 0 check (avg_rating between 0 and 5),
  difficulty numeric(3,1) not null default 0 check (difficulty between 0 and 5),
  workload_hours integer not null default 0 check (workload_hours between 0 and 60),
  attendance_required boolean not null default false,
  grade_distribution jsonb not null default '{"A":0,"B":0,"C":0,"D":0,"F":0}'::jsonb,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  course_id text not null references public.courses(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  professor_name text not null,
  semester text not null check (semester in ('Fall', 'Spring', 'Summer', 'Winter')),
  year integer not null check (year between 2020 and 2100),
  rating integer not null check (rating between 1 and 5),
  difficulty integer not null check (difficulty between 1 and 5),
  workload_hours integer not null check (workload_hours between 1 and 40),
  attendance_required boolean not null,
  would_take_again boolean not null,
  grade text not null check (grade in ('A', 'B', 'C', 'D', 'F')),
  reviewer_type text not null check (reviewer_type in ('Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate')),
  comment text not null check (char_length(trim(comment)) >= 20),
  status text not null default 'pending' check (status in ('pending', 'approved', 'reported')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, user_id, semester, year)
);

create table if not exists public.saved_courses (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  course_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, course_id)
);
alter table public.saved_courses drop constraint if exists saved_courses_course_id_fkey;

create table if not exists public.planner_items (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  course_id text not null,
  task text not null check (char_length(trim(task)) between 2 and 160),
  due_date date not null,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_reports (
  review_id text not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reason text not null check (char_length(trim(reason)) between 5 and 240),
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table if not exists public.review_tags (
  review_id uuid not null references public.reviews(id) on delete cascade,
  tag text not null check (char_length(tag) between 2 and 40),
  primary key (review_id, tag)
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  course_id text not null references public.courses(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  resource_type text not null check (resource_type in ('notes', 'pyq', 'lab', 'other')),
  storage_path text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'reported')),
  created_at timestamptz not null default now()
);

alter table public.departments enable row level security;
alter table public.professors enable row level security;
alter table public.users enable row level security;
alter table public.courses enable row level security;
alter table public.reviews enable row level security;
alter table public.saved_courses enable row level security;
alter table public.planner_items enable row level security;
alter table public.review_reports enable row level security;
alter table public.review_tags enable row level security;
alter table public.resources enable row level security;

drop policy if exists "Catalog is readable" on public.departments;
create policy "Catalog is readable" on public.departments for select to anon, authenticated using (true);
drop policy if exists "Professors are readable" on public.professors;
create policy "Professors are readable" on public.professors for select to anon, authenticated using (true);
drop policy if exists "Courses are readable" on public.courses;
create policy "Courses are readable" on public.courses for select to anon, authenticated using (true);

drop policy if exists "Users read own profile" on public.users;
create policy "Users read own profile" on public.users for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "Users create own profile" on public.users;
create policy "Users create own profile" on public.users for insert to authenticated with check ((select auth.uid()) = id and lower(email) = lower((select auth.jwt() ->> 'email')));
drop policy if exists "Users update own profile" on public.users;
create policy "Users update own profile" on public.users for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "Approved reviews are readable" on public.reviews;
create policy "Approved reviews are readable" on public.reviews for select to anon, authenticated using (status = 'approved' or (select auth.uid()) = user_id or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Verified students create reviews" on public.reviews;
create policy "Verified students create reviews" on public.reviews for insert to authenticated with check ((select auth.uid()) = user_id and lower((select auth.jwt() ->> 'email')) like '%@srmist.edu.in' and status = 'pending');
drop policy if exists "Students update own reviews" on public.reviews;
create policy "Students update own reviews" on public.reviews for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id and status = 'pending');
drop policy if exists "Students delete own reviews" on public.reviews;
create policy "Students delete own reviews" on public.reviews for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Students read own saved courses" on public.saved_courses;
create policy "Students read own saved courses" on public.saved_courses for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Students save own courses" on public.saved_courses;
create policy "Students save own courses" on public.saved_courses for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Students remove own saved courses" on public.saved_courses;
create policy "Students remove own saved courses" on public.saved_courses for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Students read own planner" on public.planner_items;
create policy "Students read own planner" on public.planner_items for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Students create own planner items" on public.planner_items;
create policy "Students create own planner items" on public.planner_items for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Students update own planner items" on public.planner_items;
create policy "Students update own planner items" on public.planner_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Students delete own planner items" on public.planner_items;
create policy "Students delete own planner items" on public.planner_items for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Students create review reports" on public.review_reports;
create policy "Students create review reports" on public.review_reports for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Students read own reports" on public.review_reports;
create policy "Students read own reports" on public.review_reports for select to authenticated using ((select auth.uid()) = user_id or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Approved review tags are readable" on public.review_tags;
create policy "Approved review tags are readable" on public.review_tags for select to anon, authenticated using (exists (select 1 from public.reviews where reviews.id = review_id and (reviews.status = 'approved' or reviews.user_id = (select auth.uid()))));
drop policy if exists "Students tag own reviews" on public.review_tags;
create policy "Students tag own reviews" on public.review_tags for insert to authenticated with check (exists (select 1 from public.reviews where reviews.id = review_id and reviews.user_id = (select auth.uid())));

drop policy if exists "Approved resources are readable" on public.resources;
create policy "Approved resources are readable" on public.resources for select to anon, authenticated using (status = 'approved' or user_id = (select auth.uid()));
drop policy if exists "Students submit resources" on public.resources;
create policy "Students submit resources" on public.resources for insert to authenticated with check (user_id = (select auth.uid()) and status = 'pending');

-- Admin authority must be assigned through auth app_metadata by a trusted server.
-- Never use user_metadata or a client-editable public profile role for authorization.
drop policy if exists "Admins manage reviews" on public.reviews;
create policy "Admins manage reviews" on public.reviews for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Admins manage catalog" on public.courses;
create policy "Admins manage catalog" on public.courses for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Admins manage professors" on public.professors;
create policy "Admins manage professors" on public.professors for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Admins manage departments" on public.departments;
create policy "Admins manage departments" on public.departments for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Admins manage resources" on public.resources;
create policy "Admins manage resources" on public.resources for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Admins manage review reports" on public.review_reports;
create policy "Admins manage review reports" on public.review_reports for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

grant usage on schema public to anon, authenticated;
grant select on public.departments, public.professors, public.courses to anon, authenticated;
grant select, insert, update, delete on public.users, public.reviews, public.saved_courses, public.planner_items, public.review_reports, public.review_tags, public.resources to authenticated;
grant usage, select on sequence public.departments_id_seq to authenticated;
