import { Award, GraduationCap, Plus, Trash2, TrendingUp } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Course, GpaRecord } from '../types';

const points: Record<GpaRecord['grade'], number> = { O: 10, 'A+': 9, A: 8, 'B+': 7, B: 6, C: 5, F: 0 };
const grades = Object.keys(points) as GpaRecord['grade'][];
function calculate(records: GpaRecord[]) { const credits = records.reduce((sum, item) => sum + item.credits, 0); return credits ? records.reduce((sum, item) => sum + points[item.grade] * item.credits, 0) / credits : 0; }

export function GpaDashboard({ courses, records, onChange }: { courses: Course[]; records: GpaRecord[]; onChange: (records: GpaRecord[]) => void }) {
  const [courseId, setCourseId] = useState(courses[0]?.id ?? ''); const [semester, setSemester] = useState('Spring 2026'); const [credits, setCredits] = useState(4); const [grade, setGrade] = useState<GpaRecord['grade']>('A');
  const semesters = useMemo(() => Array.from(new Set(records.map((item) => item.semester))), [records]); const cgpa = calculate(records);
  function add(event: React.FormEvent) { event.preventDefault(); const course = courses.find((item) => item.id === courseId); if (!course) return; onChange([...records, { id: crypto.randomUUID(), semester, courseCode: course.code, courseName: course.title, credits, grade }]); }
  return <main className="page-shell subpage"><div className="page-heading"><div><p className="eyebrow"><GraduationCap size={16} />Academic performance</p><h1>GPA dashboard</h1><p>Track semester GPA, cumulative GPA, credits, and course grades with SRM's 10-point scale.</p></div><div className="cgpa-orb"><strong>{cgpa.toFixed(2)}</strong><span>CGPA</span></div></div>
    <section className="gpa-stats">{semesters.map((name) => { const semesterRecords = records.filter((item) => item.semester === name); return <article className="card" key={name}><TrendingUp /><div><span>{name}</span><strong>{calculate(semesterRecords).toFixed(2)} SGPA</strong><small>{semesterRecords.reduce((sum,item)=>sum+item.credits,0)} credits</small></div></article>; })}<article className="card"><Award /><div><span>Total progress</span><strong>{records.reduce((sum,item)=>sum+item.credits,0)} credits</strong><small>{records.length} completed courses</small></div></article></section>
    <section className="gpa-layout"><form className="card gpa-form" onSubmit={add}><h2>Add a grade</h2><label>Course<select value={courseId} onChange={(e)=>setCourseId(e.target.value)}>{courses.map((course)=><option value={course.id} key={course.id}>{course.code} — {course.title}</option>)}</select></label><label>Semester<input value={semester} onChange={(e)=>setSemester(e.target.value)} placeholder="Spring 2026" /></label><div className="inline-fields"><label>Credits<input type="number" min="1" max="6" value={credits} onChange={(e)=>setCredits(Number(e.target.value))}/></label><label>Grade<select value={grade} onChange={(e)=>setGrade(e.target.value as GpaRecord['grade'])}>{grades.map((item)=><option key={item}>{item}</option>)}</select></label></div><button className="button primary"><Plus size={17}/>Add grade</button></form>
      <section className="card grade-ledger"><div className="section-heading"><div><p className="eyebrow">Grade ledger</p><h2>Course performance</h2></div></div>{records.length ? <div className="table-wrap"><table><thead><tr><th>Semester</th><th>Course</th><th>Credits</th><th>Grade</th><th>Points</th><th></th></tr></thead><tbody>{records.map((item)=><tr key={item.id}><td>{item.semester}</td><td><strong>{item.courseCode}</strong><span>{item.courseName}</span></td><td>{item.credits}</td><td><b className="grade-pill">{item.grade}</b></td><td>{points[item.grade]}</td><td><button className="icon-button" onClick={()=>onChange(records.filter((row)=>row.id!==item.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No grades yet.</strong><span>Add your first course result.</span></div>}</section>
    </section><p className="privacy-footnote">GPA data stays in your browser unless you later connect an authenticated cloud profile. It is never read from SRM Academia.</p>
  </main>;
}
