import { CalendarCheck, Check, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Course, PlannerItem } from '../types';
type Props = { courses: Course[]; items: PlannerItem[]; onChange: (items: PlannerItem[]) => void; loggedIn: boolean; onLogin: () => void; onNotice: (message: string) => void };
export function SemesterPlanner({ courses, items, onChange, loggedIn, onLogin, onNotice }: Props) {
  const [courseId, setCourseId] = useState(courses[0]?.id ?? ''); const [task, setTask] = useState(''); const [dueDate, setDueDate] = useState('');
  function add(event: React.FormEvent) { event.preventDefault(); if (!loggedIn) { onLogin(); return; } if (!task.trim() || !dueDate) { onNotice('Please add a task and due date.'); return; } onChange([...items, { id: crypto.randomUUID(), courseId, task: task.trim(), dueDate, done: false }]); setTask(''); onNotice('Planner item added.'); }
  return <main className="page-shell subpage"><div className="page-heading"><div><p className="eyebrow"><CalendarCheck size={16} />Semester workspace</p><h1>Plan the term, one deadline at a time</h1><p>Keep course tasks, exams, labs, and review reminders in a simple local planner.</p></div><div className="planner-progress"><strong>{items.filter((item) => item.done).length}/{items.length}</strong><span>completed</span></div></div>
    <section className="planner-layout"><form className="planner-form card" onSubmit={add}><h2>Add a deadline</h2><label>Course<select value={courseId} onChange={(e) => setCourseId(e.target.value)}>{courses.map((course) => <option value={course.id} key={course.id}>{course.code} — {course.title}</option>)}</select></label><label>Task<input value={task} onChange={(e) => setTask(e.target.value)} placeholder="e.g. Mid-sem revision" /></label><label>Due date<input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label><button className="button primary"><Plus size={17} />Add to planner</button></form>
      <div className="planner-list">{items.length ? [...items].sort((a,b) => a.dueDate.localeCompare(b.dueDate)).map((item) => { const course = courses.find((c) => c.id === item.courseId); return <article className={`planner-item card ${item.done ? 'done' : ''}`} key={item.id}><button className="check-button" onClick={() => onChange(items.map((entry) => entry.id === item.id ? { ...entry, done: !entry.done } : entry))}>{item.done && <Check />}</button><div><span>{course?.code ?? 'Course'} · {item.dueDate}</span><h3>{item.task}</h3></div><button className="icon-button" onClick={() => onChange(items.filter((entry) => entry.id !== item.id))}><Trash2 size={17} /></button></article>; }) : <div className="empty-state"><strong>Your planner is clear.</strong><span>Add a deadline to get started.</span></div>}</div>
    </section>
  </main>;
}
