import { CalendarDays, Clock3, MapPin, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Course, TimetableEntry } from '../types';
const days: TimetableEntry['day'][] = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export function TimetableCalendar({ courses, entries, onChange, onNotice }: { courses: Course[]; entries: TimetableEntry[]; onChange: (items: TimetableEntry[]) => void; onNotice: (message: string, error?: boolean) => void }) {
  const [courseId,setCourseId]=useState(courses[0]?.id??''); const [day,setDay]=useState<TimetableEntry['day']>('Monday'); const [startTime,setStartTime]=useState('09:00'); const [endTime,setEndTime]=useState('10:00'); const [room,setRoom]=useState('TP-301'); const [type,setType]=useState<TimetableEntry['type']>('Lecture');
  function add(event:React.FormEvent){event.preventDefault();if(endTime<=startTime){onNotice('End time must be after start time.',true);return;}const conflict=entries.some((item)=>item.day===day&&startTime<item.endTime&&endTime>item.startTime);if(conflict){onNotice('Timetable conflict detected for that time.',true);return;}onChange([...entries,{id:crypto.randomUUID(),courseId,day,startTime,endTime,room,type}]);onNotice('Class added to timetable.');}
  return <main className="page-shell subpage"><div className="page-heading"><div><p className="eyebrow"><CalendarDays size={16}/>Weekly schedule</p><h1>Timetable calendar</h1><p>Build a real weekly class schedule with rooms, labs, tutorials, and conflict detection.</p></div></div>
    <form className="card timetable-form" onSubmit={add}><label>Course<select value={courseId} onChange={(e)=>setCourseId(e.target.value)}>{courses.map((course)=><option value={course.id} key={course.id}>{course.code}</option>)}</select></label><label>Day<select value={day} onChange={(e)=>setDay(e.target.value as TimetableEntry['day'])}>{days.map((item)=><option key={item}>{item}</option>)}</select></label><label>Starts<input type="time" value={startTime} onChange={(e)=>setStartTime(e.target.value)}/></label><label>Ends<input type="time" value={endTime} onChange={(e)=>setEndTime(e.target.value)}/></label><label>Room<input value={room} onChange={(e)=>setRoom(e.target.value)}/></label><label>Type<select value={type} onChange={(e)=>setType(e.target.value as TimetableEntry['type'])}>{['Lecture','Lab','Tutorial'].map((item)=><option key={item}>{item}</option>)}</select></label><button className="button primary"><Plus size={17}/>Add class</button></form>
    <section className="week-calendar">{days.map((currentDay)=><div className="day-column card" key={currentDay}><h2>{currentDay.slice(0,3)}</h2><div>{entries.filter((item)=>item.day===currentDay).sort((a,b)=>a.startTime.localeCompare(b.startTime)).map((item)=>{const course=courses.find((entry)=>entry.id===item.courseId);return <article className={`calendar-event ${item.type.toLowerCase()}`} key={item.id}><span>{item.type}</span><h3>{course?.code??'Course'}</h3><p><Clock3 size={13}/>{item.startTime}–{item.endTime}</p><p><MapPin size={13}/>{item.room}</p><button onClick={()=>onChange(entries.filter((entry)=>entry.id!==item.id))}><Trash2 size={14}/></button></article>})}</div></div>)}</section>
  </main>;
}
